services:
  backend:
    build: ./RoomSplit-be
    container_name: roomsplit_backend
    volumes:
      - ./RoomSplit-be:/app
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=1
      - DB_NAME=roomsplit_db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # SEZIONE SONARQUBE
  sonarqube:
    image: sonarqube:community
    container_name: roomsplit_sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db-sonar:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - db-sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

  db-sonar:
    image: postgres:15
    container_name: roomsplit_db_sonar
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgres_sonar_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgres_sonar_data:
