sonar.organization=lor07enzo
sonar.projectKey=roomsplit
sonar.projectName=RoomSplit

sonar.python.version=3.13
sonar.sources=./RoomSplit-be,./RoomSplit-fe
sonar.exclusions=**/node_modules/**,**/migrations/**,**/.venv/**,**/venv/**

sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

# Percorso del report XML generato da pytest
sonar.python.coverage.reportPaths=RoomSplit-be/coverage.xml
# Pattern per identificare i file di test in Django
sonar.test.inclusions=RoomSplit-be/**/tests.py,RoomSplit-be/**/test_*.py,RoomSplit-be/**/tests/**/*.py