sonar.organization=lor07enzo
sonar.projectKey=roomsplit
sonar.projectName=RoomSplit

sonar.sources=./RoomSplit-be,./RoomSplit-fe

# Diciamo a Sonar dove cercare esplicitamente i test
sonar.tests=./RoomSplit-be
sonar.test.inclusions=RoomSplit-be/**/tests.py,RoomSplit-be/**/test_*.py,RoomSplit-be/**/tests/**/*.py

# Esclusioni GLOBALI (codice che Sonar non deve analizzare per niente)
sonar.exclusions=**/node_modules/**,**/migrations/**,**/.venv/**,**/venv/**

# Esclusioni dalla COPERTURA
sonar.coverage.exclusions=RoomSplit-fe/**,RoomSplit-be/manage.py,RoomSplit-be/**/settings.py,RoomSplit-be/**/asgi.py,RoomSplit-be/**/wsgi.py,RoomSplit-be/**/apps.py,RoomSplit-be/**/__init__.py

sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

# Percorso del report XML generato da pytest
sonar.python.coverage.reportPaths=RoomSplit-be/coverage.xml