# Generated by Django 6.0.4 on 2026-06-17 22:45

import django.db.models.deletion
import gruppi.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gruppo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('codice_invito', models.CharField(default=gruppi.models.genera_codice_invito, max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ruolo', models.CharField(choices=[('admin', 'Amministratore'), ('membro', 'Membro')], default='membro', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membri', to='gruppi.gruppo')),
            ],
        ),
    ]
