# Generated by Django 6.0.4 on 2026-06-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfiloPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider', models.CharField(choices=[('STRIPE', 'Stripe Connect'), ('PAYPAL', 'PayPal Sandbox'), ('MANUALE', 'Bonifico/Satispay')], default='MANUALE', max_length=12)),
                ('stato', models.CharField(choices=[('PENDING', 'In attesa'), ('SUCCESS', 'Confermato'), ('FAILED', 'Fallito')], default='PENDING', max_length=11)),
                ('external_transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
