# Generated by Django 6.0.4 on 2026-06-05 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagamenti', '0001_initial'),
        ('spese', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilopagamento',
            name='utente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilo_pagamento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transazione',
            name='creditore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamenti_ricevuti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transazione',
            name='debitore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamenti_effettuati', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transazione',
            name='spesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transazioni', to='spese.spesa'),
        ),
    ]
