# Generated by Django 6.0.4 on 2026-05-30 16:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_file', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='bollette/')),
                ('tipo_file', models.CharField(max_length=50)),
                ('status_ocr', models.CharField(choices=[('in_attesa', 'In Attesa'), ('elaborazione', 'In Elaborazione'), ('completato', 'Completato'), ('fallito', 'Fallito')], default='in_attesa', max_length=20)),
                ('importo_estratto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
