# Generated by Django 6.0.4 on 2026-05-30 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documenti', '0001_initial'),
        ('spese', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='caricato_da',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti_caricati', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='gruppo_spesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='spese.gruppospesa'),
        ),
    ]
