name: CI/CD RoomSplit - Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'RoomSplit-be/**'
      - '.github/workflows/pipeline.yml'
      - 'docker-compose.yml'

jobs:
  test-and-delivery:
    runs-on: ubuntu-latest
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      # Creazione del file .env con variabili di ambiente per i test
      - name: Crea file .env di test
        run: |
          echo "DB_NAME=roomsplit_db" > RoomSplit-be/.env
          echo "DB_USER=postgres" >> RoomSplit-be/.env
          echo "DB_PASSWORD=postgres" >> RoomSplit-be/.env
          echo "DB_HOST=db" >> RoomSplit-be/.env
          echo "DB_PORT=5432" >> RoomSplit-be/.env
          echo "TELEGRAM_BOT_TOKEN=token_finto_per_test" >> RoomSplit-be/.env
          echo "CLOUDINARY_API_KEY=chiave_finta_per_test" >> RoomSplit-be/.env
          echo "CLOUDINARY_API_SECRET=segreto_finto" >> RoomSplit-be/.env
          echo "CLOUDINARY_CLOUD_NAME=nome_finto" >> RoomSplit-be/.env

      # Avvia i container leggendo il compose principale
      - name: Avvia i container (DB e Backend)
        run: docker compose up -d db backend

      - name: Attendi che il database sia pronto
        run: sleep 15

      # Esegui i test dentro il container
      - name: Esegui i test Django con pytest
        run: docker compose exec -T -u root backend pytest --cov=. --cov-report=xml

      # Analisi SonarCloud
      - name: Scansione SonarCloud
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 

      # Fermiamo i container per pulizia
      - name: Spegni i container
        run: docker compose down

      # Setup e Delivery su Docker Hub
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login su Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push dell'immagine del Backend
        uses: docker/build-push-action@v5
        with:
          context: ./RoomSplit-be
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/roomsplit-backend:latest