# Generated by Django 6.0.4 on 2026-05-30 16:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('quantita', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('icona', models.CharField(max_length=200)),
                ('colore', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='GruppoSpesa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descrizione', models.TextField(blank=True)),
                ('is_personale', models.BooleanField(default=False)),
                ('is_ricorrente', models.BooleanField(default=False)),
                ('frequenza_numero', models.IntegerField(blank=True, default=1, null=True)),
                ('frequenza_tipo', models.CharField(blank=True, choices=[('giorni', 'Giorni'), ('settimane', 'Settimane'), ('mesi', 'Mesi'), ('anni', 'Anni')], default='mesi', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prossimo_pagamento', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListaSpesa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rimborso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipologia', models.CharField(choices=[('contanti', 'Contanti'), ('bonifico', 'Bonifico Bancario'), ('paypal', 'PayPal'), ('satispay', 'Satispay'), ('stripe', 'Stripe / Carta'), ('altro', 'Altro')], default='contanti', max_length=20)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spesa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('importo_dovuto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
