# Generated by Django 6.0.4 on 2026-05-06 13:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gruppi', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('icona', models.CharField(max_length=200)),
                ('colore', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='GruppoSpesa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descrizione', models.TextField(blank=True)),
                ('is_personale', models.BooleanField(default=False)),
                ('saldata', models.BooleanField(default=False)),
                ('is_ricorrente', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prossimo_pagamento', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spese.categoria')),
                ('gruppo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spese_gruppo', to='gruppi.gruppo')),
                ('pagatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spese_pagate', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spese_create', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListaSpesa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gruppo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liste_spesa', to='gruppi.gruppo')),
                ('gruppo_spesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liste_collegate', to='spese.gruppospesa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liste_create', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('quantita', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inserito_da', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articoli_inseriti', to=settings.AUTH_USER_MODEL)),
                ('preso_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articoli_presi', to=settings.AUTH_USER_MODEL)),
                ('lista_spesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articoli', to='spese.listaspesa')),
            ],
        ),
        migrations.CreateModel(
            name='Rimborso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipologia', models.CharField(choices=[('contanti', 'Contanti'), ('bonifico', 'Bonifico Bancario'), ('paypal', 'PayPal'), ('satispay', 'Satispay'), ('stripe', 'Stripe / Carta'), ('altro', 'Altro')], default='contanti', max_length=20)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rimborsi_inviati', to='gruppi.membro')),
                ('to_membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rimborsi_ricevuti', to='gruppi.membro')),
            ],
        ),
        migrations.CreateModel(
            name='Spesa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('importo_dovuto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_dovute', to=settings.AUTH_USER_MODEL)),
                ('gruppo_spesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_divise', to='spese.gruppospesa')),
            ],
        ),
    ]
