# Generated by Django 6.0.4 on 2026-06-05 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gruppi', '0002_initial'),
        ('spese', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='inserito_da',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articoli_inseriti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articolo',
            name='preso_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articoli_presi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gruppospesa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spese.categoria'),
        ),
        migrations.AddField(
            model_name='gruppospesa',
            name='gruppo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spese_gruppo', to='gruppi.gruppo'),
        ),
        migrations.AddField(
            model_name='gruppospesa',
            name='pagatore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spese_pagate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gruppospesa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spese_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listaspesa',
            name='gruppo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liste_spesa', to='gruppi.gruppo'),
        ),
        migrations.AddField(
            model_name='listaspesa',
            name='gruppo_spesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liste_collegate', to='spese.gruppospesa'),
        ),
        migrations.AddField(
            model_name='listaspesa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liste_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articolo',
            name='lista_spesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articoli', to='spese.listaspesa'),
        ),
        migrations.AddField(
            model_name='rimborso',
            name='from_membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rimborsi_inviati', to='gruppi.membro'),
        ),
        migrations.AddField(
            model_name='rimborso',
            name='to_membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rimborsi_ricevuti', to='gruppi.membro'),
        ),
        migrations.AddField(
            model_name='spesa',
            name='debitore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_dovute', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spesa',
            name='gruppo_spesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_divise', to='spese.gruppospesa'),
        ),
    ]
