# Generated by Django 6.0.4 on 2026-05-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruppospesa',
            name='frequenza_numero',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='gruppospesa',
            name='frequenza_tipo',
            field=models.CharField(blank=True, choices=[('giorni', 'Giorni'), ('settimane', 'Settimane'), ('mesi', 'Mesi'), ('anni', 'Anni')], default='mesi', max_length=20, null=True),
        ),
    ]
